main: me.dkim19375.utilities.Main
name: OlivMC_Utilities
version: ${pluginVersion}
description: Custom Utils for OlivMC
author: dkim19375
api-version: 1.15
commands:
  olivmcutilities:
    aliases:
      - oUtilities
      - oUtils
    description: Main Command
    usage: /oUtilities [help|dump]
    permission: oUtilities.use
permissions:
  outilities.use:
    description: Allows using the main command